# Generated by Django 5.2.7 on 2025-10-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event_queueentry_user_delete_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avg_service_minutes',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('cancelled', 'Cancelled'), ('served', 'Served')], default='waiting', max_length=20),
        ),
    ]
